/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingStep3RouteImport } from './routes/onboarding/step3'
import { Route as OnboardingStep2RouteImport } from './routes/onboarding/step2'
import { Route as OnboardingStep1RouteImport } from './routes/onboarding/step1'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthSignoutRouteImport } from './routes/auth/signout'
import { Route as AuthSetPasswordRouteImport } from './routes/auth/set-password'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AdminShippingRouteImport } from './routes/admin/shipping'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCustomerGroupsRouteImport } from './routes/admin/customer-groups'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products_/index'
import { Route as AdminPriceListsIndexRouteImport } from './routes/admin/price-lists_/index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders_/index'
import { Route as AdminDiscountsIndexRouteImport } from './routes/admin/discounts_/index'
import { Route as AdminCustomersIndexRouteImport } from './routes/admin/customers_/index'
import { Route as AdminCampaignsIndexRouteImport } from './routes/admin/campaigns_/index'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products_/new'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products_/$productId'
import { Route as AdminPriceListsNewRouteImport } from './routes/admin/price-lists_/new'
import { Route as AdminPriceListsPriceListIdRouteImport } from './routes/admin/price-lists_/$priceListId'
import { Route as AdminOrdersNewRouteImport } from './routes/admin/orders_/new'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin/orders_/$orderId'
import { Route as AdminDiscountsNewRouteImport } from './routes/admin/discounts_/new'
import { Route as AdminDiscountsDiscountIdRouteImport } from './routes/admin/discounts_/$discountId'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin/customers_/$customerId'
import { Route as AdminCampaignsNewRouteImport } from './routes/admin/campaigns_/new'
import { Route as AdminCampaignsCampaignIdRouteImport } from './routes/admin/campaigns_/$campaignId'

const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStep3Route = OnboardingStep3RouteImport.update({
  id: '/step3',
  path: '/step3',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStep2Route = OnboardingStep2RouteImport.update({
  id: '/step2',
  path: '/step2',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const OnboardingStep1Route = OnboardingStep1RouteImport.update({
  id: '/step1',
  path: '/step1',
  getParentRoute: () => OnboardingRouteRoute,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignoutRoute = AuthSignoutRouteImport.update({
  id: '/signout',
  path: '/signout',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSetPasswordRoute = AuthSetPasswordRouteImport.update({
  id: '/set-password',
  path: '/set-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminShippingRoute = AdminShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomerGroupsRoute = AdminCustomerGroupsRouteImport.update({
  id: '/customer-groups',
  path: '/customer-groups',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/products_/',
  path: '/products/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPriceListsIndexRoute = AdminPriceListsIndexRouteImport.update({
  id: '/price-lists_/',
  path: '/price-lists/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders_/',
  path: '/orders/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiscountsIndexRoute = AdminDiscountsIndexRouteImport.update({
  id: '/discounts_/',
  path: '/discounts/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers_/',
  path: '/customers/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCampaignsIndexRoute = AdminCampaignsIndexRouteImport.update({
  id: '/campaigns_/',
  path: '/campaigns/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/products_/new',
  path: '/products/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/products_/$productId',
  path: '/products/$productId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPriceListsNewRoute = AdminPriceListsNewRouteImport.update({
  id: '/price-lists_/new',
  path: '/price-lists/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPriceListsPriceListIdRoute =
  AdminPriceListsPriceListIdRouteImport.update({
    id: '/price-lists_/$priceListId',
    path: '/price-lists/$priceListId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/orders_/new',
  path: '/orders/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders_/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiscountsNewRoute = AdminDiscountsNewRouteImport.update({
  id: '/discounts_/new',
  path: '/discounts/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDiscountsDiscountIdRoute =
  AdminDiscountsDiscountIdRouteImport.update({
    id: '/discounts_/$discountId',
    path: '/discounts/$discountId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/customers_/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminCampaignsNewRoute = AdminCampaignsNewRouteImport.update({
  id: '/campaigns_/new',
  path: '/campaigns/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCampaignsCampaignIdRoute =
  AdminCampaignsCampaignIdRouteImport.update({
    id: '/campaigns_/$campaignId',
    path: '/campaigns/$campaignId',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customer-groups': typeof AdminCustomerGroupsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/admin/campaigns/$campaignId': typeof AdminCampaignsCampaignIdRoute
  '/admin/campaigns/new': typeof AdminCampaignsNewRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/price-lists/$priceListId': typeof AdminPriceListsPriceListIdRoute
  '/admin/price-lists/new': typeof AdminPriceListsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/campaigns/': typeof AdminCampaignsIndexRoute
  '/admin/customers/': typeof AdminCustomersIndexRoute
  '/admin/discounts/': typeof AdminDiscountsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/price-lists/': typeof AdminPriceListsIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customer-groups': typeof AdminCustomerGroupsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/admin/campaigns/$campaignId': typeof AdminCampaignsCampaignIdRoute
  '/admin/campaigns/new': typeof AdminCampaignsNewRoute
  '/admin/customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/discounts/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts/new': typeof AdminDiscountsNewRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/price-lists/$priceListId': typeof AdminPriceListsPriceListIdRoute
  '/admin/price-lists/new': typeof AdminPriceListsNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/campaigns': typeof AdminCampaignsIndexRoute
  '/admin/customers': typeof AdminCustomersIndexRoute
  '/admin/discounts': typeof AdminDiscountsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/price-lists': typeof AdminPriceListsIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/onboarding': typeof OnboardingRouteRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/customer-groups': typeof AdminCustomerGroupsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/shipping': typeof AdminShippingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/set-password': typeof AuthSetPasswordRoute
  '/auth/signout': typeof AuthSignoutRoute
  '/auth/signup': typeof AuthSignupRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/onboarding/step1': typeof OnboardingStep1Route
  '/onboarding/step2': typeof OnboardingStep2Route
  '/onboarding/step3': typeof OnboardingStep3Route
  '/admin/campaigns_/$campaignId': typeof AdminCampaignsCampaignIdRoute
  '/admin/campaigns_/new': typeof AdminCampaignsNewRoute
  '/admin/customers_/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin/discounts_/$discountId': typeof AdminDiscountsDiscountIdRoute
  '/admin/discounts_/new': typeof AdminDiscountsNewRoute
  '/admin/orders_/$orderId': typeof AdminOrdersOrderIdRoute
  '/admin/orders_/new': typeof AdminOrdersNewRoute
  '/admin/price-lists_/$priceListId': typeof AdminPriceListsPriceListIdRoute
  '/admin/price-lists_/new': typeof AdminPriceListsNewRoute
  '/admin/products_/$productId': typeof AdminProductsProductIdRoute
  '/admin/products_/new': typeof AdminProductsNewRoute
  '/admin/campaigns_/': typeof AdminCampaignsIndexRoute
  '/admin/customers_/': typeof AdminCustomersIndexRoute
  '/admin/discounts_/': typeof AdminDiscountsIndexRoute
  '/admin/orders_/': typeof AdminOrdersIndexRoute
  '/admin/price-lists_/': typeof AdminPriceListsIndexRoute
  '/admin/products_/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customer-groups'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/settings'
    | '/admin/shipping'
    | '/auth/login'
    | '/auth/set-password'
    | '/auth/signout'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/admin/campaigns/$campaignId'
    | '/admin/campaigns/new'
    | '/admin/customers/$customerId'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/price-lists/$priceListId'
    | '/admin/price-lists/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/campaigns/'
    | '/admin/customers/'
    | '/admin/discounts/'
    | '/admin/orders/'
    | '/admin/price-lists/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customer-groups'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/settings'
    | '/admin/shipping'
    | '/auth/login'
    | '/auth/set-password'
    | '/auth/signout'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/admin/campaigns/$campaignId'
    | '/admin/campaigns/new'
    | '/admin/customers/$customerId'
    | '/admin/discounts/$discountId'
    | '/admin/discounts/new'
    | '/admin/orders/$orderId'
    | '/admin/orders/new'
    | '/admin/price-lists/$priceListId'
    | '/admin/price-lists/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/campaigns'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/orders'
    | '/admin/price-lists'
    | '/admin/products'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/onboarding'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/customer-groups'
    | '/admin/dashboard'
    | '/admin/inventory'
    | '/admin/settings'
    | '/admin/shipping'
    | '/auth/login'
    | '/auth/set-password'
    | '/auth/signout'
    | '/auth/signup'
    | '/auth/verify-email'
    | '/onboarding/step1'
    | '/onboarding/step2'
    | '/onboarding/step3'
    | '/admin/campaigns_/$campaignId'
    | '/admin/campaigns_/new'
    | '/admin/customers_/$customerId'
    | '/admin/discounts_/$discountId'
    | '/admin/discounts_/new'
    | '/admin/orders_/$orderId'
    | '/admin/orders_/new'
    | '/admin/price-lists_/$priceListId'
    | '/admin/price-lists_/new'
    | '/admin/products_/$productId'
    | '/admin/products_/new'
    | '/admin/campaigns_/'
    | '/admin/customers_/'
    | '/admin/discounts_/'
    | '/admin/orders_/'
    | '/admin/price-lists_/'
    | '/admin/products_/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  OnboardingRouteRoute: typeof OnboardingRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/step3': {
      id: '/onboarding/step3'
      path: '/step3'
      fullPath: '/onboarding/step3'
      preLoaderRoute: typeof OnboardingStep3RouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/step2': {
      id: '/onboarding/step2'
      path: '/step2'
      fullPath: '/onboarding/step2'
      preLoaderRoute: typeof OnboardingStep2RouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/onboarding/step1': {
      id: '/onboarding/step1'
      path: '/step1'
      fullPath: '/onboarding/step1'
      preLoaderRoute: typeof OnboardingStep1RouteImport
      parentRoute: typeof OnboardingRouteRoute
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signout': {
      id: '/auth/signout'
      path: '/signout'
      fullPath: '/auth/signout'
      preLoaderRoute: typeof AuthSignoutRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/set-password': {
      id: '/auth/set-password'
      path: '/set-password'
      fullPath: '/auth/set-password'
      preLoaderRoute: typeof AuthSetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/admin/shipping': {
      id: '/admin/shipping'
      path: '/shipping'
      fullPath: '/admin/shipping'
      preLoaderRoute: typeof AdminShippingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customer-groups': {
      id: '/admin/customer-groups'
      path: '/customer-groups'
      fullPath: '/admin/customer-groups'
      preLoaderRoute: typeof AdminCustomerGroupsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products_/': {
      id: '/admin/products_/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/price-lists_/': {
      id: '/admin/price-lists_/'
      path: '/price-lists'
      fullPath: '/admin/price-lists/'
      preLoaderRoute: typeof AdminPriceListsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders_/': {
      id: '/admin/orders_/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/discounts_/': {
      id: '/admin/discounts_/'
      path: '/discounts'
      fullPath: '/admin/discounts/'
      preLoaderRoute: typeof AdminDiscountsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers_/': {
      id: '/admin/customers_/'
      path: '/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/campaigns_/': {
      id: '/admin/campaigns_/'
      path: '/campaigns'
      fullPath: '/admin/campaigns/'
      preLoaderRoute: typeof AdminCampaignsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products_/new': {
      id: '/admin/products_/new'
      path: '/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products_/$productId': {
      id: '/admin/products_/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/price-lists_/new': {
      id: '/admin/price-lists_/new'
      path: '/price-lists/new'
      fullPath: '/admin/price-lists/new'
      preLoaderRoute: typeof AdminPriceListsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/price-lists_/$priceListId': {
      id: '/admin/price-lists_/$priceListId'
      path: '/price-lists/$priceListId'
      fullPath: '/admin/price-lists/$priceListId'
      preLoaderRoute: typeof AdminPriceListsPriceListIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders_/new': {
      id: '/admin/orders_/new'
      path: '/orders/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders_/$orderId': {
      id: '/admin/orders_/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/discounts_/new': {
      id: '/admin/discounts_/new'
      path: '/discounts/new'
      fullPath: '/admin/discounts/new'
      preLoaderRoute: typeof AdminDiscountsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/discounts_/$discountId': {
      id: '/admin/discounts_/$discountId'
      path: '/discounts/$discountId'
      fullPath: '/admin/discounts/$discountId'
      preLoaderRoute: typeof AdminDiscountsDiscountIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers_/$customerId': {
      id: '/admin/customers_/$customerId'
      path: '/customers/$customerId'
      fullPath: '/admin/customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/campaigns_/new': {
      id: '/admin/campaigns_/new'
      path: '/campaigns/new'
      fullPath: '/admin/campaigns/new'
      preLoaderRoute: typeof AdminCampaignsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/campaigns_/$campaignId': {
      id: '/admin/campaigns_/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/admin/campaigns/$campaignId'
      preLoaderRoute: typeof AdminCampaignsCampaignIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCustomerGroupsRoute: typeof AdminCustomerGroupsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminShippingRoute: typeof AdminShippingRoute
  AdminCampaignsCampaignIdRoute: typeof AdminCampaignsCampaignIdRoute
  AdminCampaignsNewRoute: typeof AdminCampaignsNewRoute
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
  AdminDiscountsDiscountIdRoute: typeof AdminDiscountsDiscountIdRoute
  AdminDiscountsNewRoute: typeof AdminDiscountsNewRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminPriceListsPriceListIdRoute: typeof AdminPriceListsPriceListIdRoute
  AdminPriceListsNewRoute: typeof AdminPriceListsNewRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminCampaignsIndexRoute: typeof AdminCampaignsIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminDiscountsIndexRoute: typeof AdminDiscountsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPriceListsIndexRoute: typeof AdminPriceListsIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCustomerGroupsRoute: AdminCustomerGroupsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminShippingRoute: AdminShippingRoute,
  AdminCampaignsCampaignIdRoute: AdminCampaignsCampaignIdRoute,
  AdminCampaignsNewRoute: AdminCampaignsNewRoute,
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
  AdminDiscountsDiscountIdRoute: AdminDiscountsDiscountIdRoute,
  AdminDiscountsNewRoute: AdminDiscountsNewRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminPriceListsPriceListIdRoute: AdminPriceListsPriceListIdRoute,
  AdminPriceListsNewRoute: AdminPriceListsNewRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminCampaignsIndexRoute: AdminCampaignsIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminDiscountsIndexRoute: AdminDiscountsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPriceListsIndexRoute: AdminPriceListsIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSetPasswordRoute: typeof AuthSetPasswordRoute
  AuthSignoutRoute: typeof AuthSignoutRoute
  AuthSignupRoute: typeof AuthSignupRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSetPasswordRoute: AuthSetPasswordRoute,
  AuthSignoutRoute: AuthSignoutRoute,
  AuthSignupRoute: AuthSignupRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface OnboardingRouteRouteChildren {
  OnboardingStep1Route: typeof OnboardingStep1Route
  OnboardingStep2Route: typeof OnboardingStep2Route
  OnboardingStep3Route: typeof OnboardingStep3Route
}

const OnboardingRouteRouteChildren: OnboardingRouteRouteChildren = {
  OnboardingStep1Route: OnboardingStep1Route,
  OnboardingStep2Route: OnboardingStep2Route,
  OnboardingStep3Route: OnboardingStep3Route,
}

const OnboardingRouteRouteWithChildren = OnboardingRouteRoute._addFileChildren(
  OnboardingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  OnboardingRouteRoute: OnboardingRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
